name: Build


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache-dependency-path: gofeed/go.sum

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    # Verify the SHA-sum
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: gradle build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
